# -*- coding: utf-8 -*-
"""Part2codeLumumba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16X3rnxSv9CCaOdxsWf1XEsbytDlSffI2
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_style("dark")

### importing the dataset from github

url = "https://github.com/LumumbaAssumani/Exploratory-Analysis---I.40/raw/main/dataset2.csv"
df = pd.read_csv(url)
df.columns

"""### removing values that are Nan or missing

I would recommend querying why these values were inputted incorrectly and whty there are missing values. is this human error of machine, could you remeasure them if they have a nunique ID number?
"""

nullcheck = df.isnull()
nulldf = df[nullcheck.any(axis=1)]
#print(nulldf)

#df.info()

df.shape

df.columns

sns.set_style("dark")
sns.countplot(data=df, x='Parts')
plt.show()

df['Parts'].value_counts().plot(kind='pie', autopct='%1.1f%%', fontsize = 14)
plt.savefig('oldpie.jpeg', format='jpeg', bbox_inches='tight')
plt.show()

# Drop every row that has NAN
df_drop = df.dropna(how='any')
nulldf_1= df_drop[nullcheck.any(axis=1)]
#print(df_drop)

checking = df_drop.isnull()
print(checking.sum())

nullvals = df.isnull()
nulltab = df[nullvals.any(axis=1)]
print(nulltab)

df_drop.shape

"""### Plotting Histogram"""

sns.set_style("dark")

#### providing the spread of my data set. Each part is categorical

fig, axes = plt.subplots(1,3)
fig.set_size_inches(15,5)
sns.boxplot(data=df_drop, x = 'Parts',y ='length', hue ='Parts' ,ax = axes[0],legend='brief')
sns.boxplot(data=df_drop,x='Parts', y = 'mass', hue='Parts',ax= axes[1], legend='brief')
sns.boxplot(data=df_drop,x='Parts', y = 'width', hue='Parts',ax = axes[2], legend = 'full')
sns.set_style('dark')
axes[0].set_title('Length', fontsize= 12, fontweight='bold');
axes[1].set_title('Mass', fontsize= 12, fontweight='bold');
axes[2].set_title('Width', fontsize= 12, fontweight='bold');
fig.savefig('Boxplot_I40.jpeg', format='jpeg', bbox_inches='tight')
plt.show()

# descriptive statistics
df_drop.groupby('Parts').describe()

def get_outliers(data, x_col, cols):
    outliers = set()

    for col in cols:
        groups = data.groupby(x_col)[col]
        IQR   = groups.quantile(0.75) - groups.quantile(0.25)
        upper = groups.quantile(0.75) + 1.5 * IQR
        lower = groups.quantile(0.25) - 1.5 * IQR

        for idx, row in data.iterrows():
            val  = row[col]
            part = row[x_col]
            if val > upper[part] or val < lower[part]:
                outliers.add(idx)

    return data.loc[sorted(outliers)]

outliers_df = get_outliers(df_drop, 'Parts', ['length', 'mass', 'width'])
display(outliers_df)

"""### plotting Histogram"""

import plotly.express as px

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

plt.ylabel('Frequency')

sns.histplot(data=df_drop, x='length', hue='Parts',bins = 30, ax=axes[0], kde=True,element='step')
sns.histplot(data=df_drop, x='mass',   hue='Parts',bins = 30,ax=axes[1], kde = True,element='step')
sns.histplot(data=df_drop, x='width',  hue='Parts',bins = 30, ax=axes[2], kde =True,element = 'step')

axes[0].set_title('Length', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Length', fontsize=14)
axes[0].tick_params(axis='both', labelsize=14)


axes[1].set_title('Mass',   fontsize=12, fontweight='bold')
axes[1].set_xlabel('Length', fontsize=14)
axes[1].tick_params(axis='both', labelsize=14)

axes[2].set_title('Width',  fontsize=12, fontweight='bold')
axes[2].set_xlabel('Length', fontsize=14)
axes[2].tick_params(axis='both', labelsize=14)




plt.tight_layout()
fig.savefig('Histogram.jpeg', format='jpeg', bbox_inches='tight')

plt.show()

P1 = df_drop.loc[df_drop['Parts'] == 'P1'].copy()
P2 = df_drop.loc[df_drop['Parts'] == 'P2'].copy()
P3 = df_drop.loc[df_drop['Parts'] == 'P3'].copy()

"""### Pie chart"""

df_drop['Parts'].value_counts().plot(kind='pie', autopct='%1.1f%%', fontsize= 14)
plt.savefig('cleanpie.jpeg', format='jpeg', bbox_inches='tight')
plt.show()

sns.countplot(data=df_drop, x='Parts')
plt.show()

"""# Multivariate Analysis"""

sns.pairplot(df_drop, hue='Parts')
plt.rc('axes', labelsize=12)
plt.rc('xtick', labelsize=12)
plt.rc('ytick', labelsize=12)
plt.savefig('pairplot.jpeg', format='jpeg', bbox_inches='tight')
plt.show()

P1 = df_drop.loc[df_drop['Parts'] == 'P1'].copy()
P2 = df_drop.loc[df_drop['Parts'] == 'P2'].copy()
P3 = df_drop.loc[df_drop['Parts'] == 'P3'].copy()

def plot_corr(df,part,name):
    co_mtx = df.corr(numeric_only=True)
    sns.heatmap(co_mtx,cmap="coolwarm", annot=True,vmin=0 ,vmax=1, annot_kws={"size": 14})
    plt.title(f'{part} Correlation Matrix')
    plt.xticks(fontsize=14)
    plt.yticks(fontsize=14)
    plt.savefig(f'{name}.jpeg', format='jpeg', bbox_inches='tight')
    plt.show()

plot_corr(P1,'P1','P1corr')
plot_corr(P2,'P2','P2corr')
plot_corr(P3,'P3','P3corr')

## percentage of missing parts in all columns


df_drop.groupby('Parts').describe()

df.groupby('Parts').describe()

P1_per = ((86-84)/86)*100
P2_per= ((22-21)/22)*100
P3_per = ((78-75)/78)*100

print(round(P1_per,2))
print(round(P2_per,2))
print(round(P3_per,2))